name: lint
version: 1.5.3
description: An opinionated, community-driven set of lint rules for Dart and Flutter projects. Like pedantic but stricter
homepage: https://github.com/passsy/dart-lint

environment:
  sdk: '>=2.12.0 <3.0.0'
